package com.infinity.infoway.vimal.model;

public class RetailerVisitCallModel {
    public int RETAILER_VISIT_ID;
    public String RETAILER_VISIT_CALL_TYPE,RETAILER_VISIT_SHOP_NAME,RETAILER_VISIT_PERSON_NMAE,RETAILER_VISIT_MOBILE,RETAILER_VISIT_NEXT_FOLOWUP_DATE,
            RETAILER_VISIT_CITY_ID,RETAILER_VISIT_ADDRESS1,RETAILER_VISIT_ADDRESS2,RETAILER_VISIT_SUGGESTIONS,RETAILER_VISIT_LATITUDE,
            RETAILER_VISIT_LONGITUDE,RETAILER_VISIT_LOC_ADDRESS,RETAILER_VISIT_GPS_FLAG,RETAILER_VISIT_LOC_ACCURACY;

    public byte [] RETAILER_VISIT_PHOTO;

    public int getRETAILER_VISIT_ID() {
        return RETAILER_VISIT_ID;
    }

    public void setRETAILER_VISIT_ID(int RETAILER_VISIT_ID) {
        this.RETAILER_VISIT_ID = RETAILER_VISIT_ID;
    }

    public String getRETAILER_VISIT_CALL_TYPE() {
        return RETAILER_VISIT_CALL_TYPE;
    }

    public void setRETAILER_VISIT_CALL_TYPE(String RETAILER_VISIT_CALL_TYPE) {
        this.RETAILER_VISIT_CALL_TYPE = RETAILER_VISIT_CALL_TYPE;
    }

    public String getRETAILER_VISIT_SHOP_NAME() {
        return RETAILER_VISIT_SHOP_NAME;
    }

    public void setRETAILER_VISIT_SHOP_NAME(String RETAILER_VISIT_SHOP_NAME) {
        this.RETAILER_VISIT_SHOP_NAME = RETAILER_VISIT_SHOP_NAME;
    }

    public String getRETAILER_VISIT_PERSON_NMAE() {
        return RETAILER_VISIT_PERSON_NMAE;
    }

    public void setRETAILER_VISIT_PERSON_NMAE(String RETAILER_VISIT_PERSON_NMAE) {
        this.RETAILER_VISIT_PERSON_NMAE = RETAILER_VISIT_PERSON_NMAE;
    }

    public String getRETAILER_VISIT_MOBILE() {
        return RETAILER_VISIT_MOBILE;
    }

    public void setRETAILER_VISIT_MOBILE(String RETAILER_VISIT_MOBILE) {
        this.RETAILER_VISIT_MOBILE = RETAILER_VISIT_MOBILE;
    }

    public String getRETAILER_VISIT_NEXT_FOLOWUP_DATE() {
        return RETAILER_VISIT_NEXT_FOLOWUP_DATE;
    }

    public void setRETAILER_VISIT_NEXT_FOLOWUP_DATE(String RETAILER_VISIT_NEXT_FOLOWUP_DATE) {
        this.RETAILER_VISIT_NEXT_FOLOWUP_DATE = RETAILER_VISIT_NEXT_FOLOWUP_DATE;
    }

    public String getRETAILER_VISIT_CITY_ID() {
        return RETAILER_VISIT_CITY_ID;
    }

    public void setRETAILER_VISIT_CITY_ID(String RETAILER_VISIT_CITY_ID) {
        this.RETAILER_VISIT_CITY_ID = RETAILER_VISIT_CITY_ID;
    }

    public String getRETAILER_VISIT_ADDRESS1() {
        return RETAILER_VISIT_ADDRESS1;
    }

    public void setRETAILER_VISIT_ADDRESS1(String RETAILER_VISIT_ADDRESS1) {
        this.RETAILER_VISIT_ADDRESS1 = RETAILER_VISIT_ADDRESS1;
    }

    public String getRETAILER_VISIT_ADDRESS2() {
        return RETAILER_VISIT_ADDRESS2;
    }

    public void setRETAILER_VISIT_ADDRESS2(String RETAILER_VISIT_ADDRESS2) {
        this.RETAILER_VISIT_ADDRESS2 = RETAILER_VISIT_ADDRESS2;
    }

    public String getRETAILER_VISIT_SUGGESTIONS() {
        return RETAILER_VISIT_SUGGESTIONS;
    }

    public void setRETAILER_VISIT_SUGGESTIONS(String RETAILER_VISIT_SUGGESTIONS) {
        this.RETAILER_VISIT_SUGGESTIONS = RETAILER_VISIT_SUGGESTIONS;
    }

    public byte[] getRETAILER_VISIT_PHOTO() {
        return RETAILER_VISIT_PHOTO;
    }

    public void setRETAILER_VISIT_PHOTO(byte [] RETAILER_VISIT_PHOTO) {
        this.RETAILER_VISIT_PHOTO = RETAILER_VISIT_PHOTO;
    }

    public String getRETAILER_VISIT_LATITUDE() {
        return RETAILER_VISIT_LATITUDE;
    }

    public void setRETAILER_VISIT_LATITUDE(String RETAILER_VISIT_LATITUDE) {
        this.RETAILER_VISIT_LATITUDE = RETAILER_VISIT_LATITUDE;
    }

    public String getRETAILER_VISIT_LONGITUDE() {
        return RETAILER_VISIT_LONGITUDE;
    }

    public void setRETAILER_VISIT_LONGITUDE(String RETAILER_VISIT_LONGITUDE) {
        this.RETAILER_VISIT_LONGITUDE = RETAILER_VISIT_LONGITUDE;
    }

    public String getRETAILER_VISIT_LOC_ADDRESS() {
        return RETAILER_VISIT_LOC_ADDRESS;
    }

    public void setRETAILER_VISIT_LOC_ADDRESS(String RETAILER_VISIT_LOC_ADDRESS) {
        this.RETAILER_VISIT_LOC_ADDRESS = RETAILER_VISIT_LOC_ADDRESS;
    }

    public String getRETAILER_VISIT_GPS_FLAG() {
        return RETAILER_VISIT_GPS_FLAG;
    }

    public void setRETAILER_VISIT_GPS_FLAG(String RETAILER_VISIT_GPS_FLAG) {
        this.RETAILER_VISIT_GPS_FLAG = RETAILER_VISIT_GPS_FLAG;
    }

    public String getRETAILER_VISIT_LOC_ACCURACY() {
        return RETAILER_VISIT_LOC_ACCURACY;
    }

    public void setRETAILER_VISIT_LOC_ACCURACY(String RETAILER_VISIT_LOC_ACCURACY) {
        this.RETAILER_VISIT_LOC_ACCURACY = RETAILER_VISIT_LOC_ACCURACY;
    }
}
